= Control connection

The control connection is a dedicated connection used for administrative tasks:

* querying system tables to learn about the cluster's xref:core/nodeMetadata.adoc[topology] and xref:core/schemaMetadata.adoc[schema];
* checking xref:core/schemaMetadata.adoc#_schema_agreement[schema agreement];
* reacting to server events, which are used to notify the driver of external topology or schema changes.

When the driver starts, the control connection is established to the first contacted node.
If that node goes down, a xref:core/reconnection.adoc[reconnection] is started to find another node;
it is governed by the same policy as regular connections (`advanced.reconnection-policy` options in the xref:core/configuration.adoc[configuration]), and tries the nodes according to a query plan from the xref:core/loadBalancing.adoc[load balancing policy].

The control connection is managed independently from xref:core/pooling.adoc[regular pooled connections], and used exclusively for administrative requests.
It shows up in https://docs.datastax.com/en/drivers/java/4.13/com/datastax/oss/driver/api/core/metadata/Node.html#getOpenConnections--[Node.getOpenConnections], as well as the `pool.open-connections` xref:core/metrics.adoc[metric];
for example, if you've configured a pool size of 2, the control node will show 3 connections.

There are a few options to fine tune the control connection behavior in the `advanced.control-connection` and `advanced.metadata` sections;
see the xref:core/metadata.adoc[metadata] pages and the xref:core/configurationReference.adoc[reference configuration] for all the details.
