= Integration

== Quick overview

* sample project structures for Maven and Gradle.
* explanations about <<driver-dependencies,driver dependencies>> and when they can be manually excluded.

NOTE: guidelines to build a GraalVM native image can be found xref:core/graalvm.adoc[here].

'''

== Which artifact(s) should I use?

There are multiple driver artifacts under the group id https://search.maven.org/search?q=g:com.datastax.oss[com.datastax.oss].
Here's how to pick the right dependencies:
    
 
[cols="1,1,1",options=header]
|===

|Features |Artifact(s) |Comments

|Core functionality: executing queries with `CqlSession.execute()`, processing the results with `ResultSet`, etc.
|`java‑driver‑core`
|

|Same as the above, but without explicit dependencies to Netty, Jackson or ESRI.
|`java‑driver‑core‑shaded`
|Replaces java‑driver‑core. See xref:core/shadedJar.adoc[Shaded JAR].

|Query builder: generating CQL query strings programmatically.
|`java‑driver‑query‑builder	`
|

|Object mapper: generating the boilerplate to execute queries and convert the results into your own domain classes.
|`java‑driver‑mapper‑processor` or `java‑driver‑mapper‑runtime`
|Both artifacts are needed. See xref:mapper/config/index.adoc[object mapper configuration].

|Instrumenting the driver and gathering metrics using the Micrometer metrics library.
|`java‑driver‑metrics‑micrometer`
|See xref:core/metrics.adoc.

|Instrumenting the driver and gathering metrics using the MicroProfile Metrics library.
|`java‑driver‑metrics‑microprofile`
|See xref:core/metrics.adoc.

|Bill of Materials: can help manage versions if you use multiple driver artifacts.
|`java-driver-bom`
|See xref:core/bom.adoc[BOM].

|Writing integration tests that run the driver against Cassandra or Simulacron.
|`java-driver-test-infra`
|Those APIs are not covered in this manual, but you can look at the driver’s 
link:https://github.com/datastax/java-driver/blob/4.x/CONTRIBUTING.md#integration-tests[contribution guidelines]
and link:https://github.com/datastax/java-driver/tree/4.x/integration-tests[internal tests] for guidance.

|===

== Minimal project structure

We publish the driver to https://search.maven.org/#search%7Cga%7C1%7Ccom.datastax.oss[Maven central].
Most modern build tools can download the dependency automatically.

=== Maven

Create the following 4 files:

 $ find . -type f
 ./pom.xml
 ./src/main/resources/application.conf
 ./src/main/resources/logback.xml
 ./src/main/java/Main.java

==== Project descriptor

`pom.xml` is the https://maven.apache.org/guides/introduction/introduction-to-the-pom.html[Project Object Model] that describes your application.
We declare the dependencies, and tell Maven that we're going to use Java 8:

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.example.yourcompany</groupId>
  <artifactId>yourapp</artifactId>
  <version>1.0.0-SNAPSHOT</version>

  <dependencies>
    <dependency>
      <groupId>com.datastax.oss</groupId>
      <artifactId>java-driver-core</artifactId>
      <version>${driver.version}</version>
    </dependency>
    <dependency>
      <groupId>ch.qos.logback</groupId>
      <artifactId>logback-classic</artifactId>
      <version>1.2.3</version>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
----

==== Application configuration

`application.conf` is not stricly necessary, but it illustrates an important point about the driver's xref:core/configuration.adoc[configuration]: you override any of the driver's default options here.

----
datastax-java-driver {
  basic.session-name = poc
}
----

In this case, we just specify a custom name for our session, it will appear in the logs.

==== Logging configuration

For this example, we choose Logback as our xref:core/logging.adoc[logging framework] (we added the dependency in `pom.xml`).
`logback.xml` configures it to send the driver's `INFO` logs to the console.

[source,xml]
----
<configuration>
  <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
      <pattern>%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
    </encoder>
  </appender>
  <root level="WARN">
    <appender-ref ref="STDOUT"/>
  </root>
  <logger name="com.datastax.oss.driver" level= "INFO"/>
</configuration>
----

Again, this is not strictly necessary: a truly minimal example could run without the Logback dependency, or this file;
but the default behavior is a bit verbose.

==== Main class

`Main.java` is the canonical example introduced in our xref:core/index.adoc#quick-start[quick start];
it connects to Cassandra, queries the server version and prints it:

[source,java]
----
import com.datastax.oss.driver.api.core.CqlSession;
import com.datastax.oss.driver.api.core.cql.ResultSet;

public class Main {
  public static void main(String[] args) {
    try (CqlSession session = CqlSession.builder().build()) {
      ResultSet rs = session.execute("SELECT release_version FROM system.local");
      System.out.println(rs.one().getString(0));
    }
  }
}
----

Make sure you have a Cassandra instance running on 127.0.0.1:9042 (otherwise, you use https://docs.datastax.com/en/drivers/java/4.13/com/datastax/oss/driver/api/core/session/SessionBuilder.html#addContactPoint-java.net.InetSocketAddress-[CqlSession.builder().addContactPoint()] to use a different address).

==== Running

To launch the program from the command line, use:

 $ mvn compile exec:java -Dexec.mainClass=Main

You should see output similar to:

----
...
[INFO] ------------------------------------------------------------------------
[INFO] Building yourapp 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
... (at this point, Maven will download the dependencies the first time)
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ yourapp ---
[WARNING] Using platform encoding (UTF-8 actually) to copy filtered resources, i.e. build is platform dependent!
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:2.5.1:compile (default-compile) @ yourapp ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- exec-maven-plugin:1.3.1:java (default-cli) @ yourapp ---
11:39:45.355 [Main.main()] INFO  c.d.o.d.i.c.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.0.1
11:39:45.648 [poc-admin-0] INFO  c.d.o.d.internal.core.time.Clock - Using native clock for microsecond precision
11:39:45.649 [poc-admin-0] INFO  c.d.o.d.i.c.metadata.MetadataManager - [poc] No contact points provided, defaulting to /127.0.0.1:9042
3.11.2
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 11.777 s
[INFO] Finished at: 2018-06-18T11:32:49-08:00
[INFO] Final Memory: 16M/277M
[INFO] ------------------------------------------------------------------------
----

=== Gradle

https://guides.gradle.org/creating-new-gradle-builds/[Initialize a new project] with Gradle.

Modify `build.gradle` to add the dependencies:

[source,groovy]
----
group 'com.example.yourcompany'
version '1.0.0-SNAPSHOT'

apply plugin: 'java'

sourceCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    compile group: 'com.datastax.oss', name: 'java-driver-core', version: '${driver.version}'
    compile group: 'ch.qos.logback', name: 'logback-classic', version: '1.2.3'
}
----

Then place <<application-configuration,application.conf>>, <<logging-configuration,logback.xml>> and <<main-class,Main.java>> in the same locations, and with the same contents, as in the Maven example:

----
./src/main/resources/application.conf
./src/main/resources/logback.xml
./src/main/java/Main.java
----

Optionally, if you want to run from the command line, add the following at the end of `build.gradle`:

[source,groovy]
----
task execute(type:JavaExec) {
    main = 'Main'
    classpath = sourceSets.main.runtimeClasspath
}
----

Then launch with:

 $ ./gradlew execute

You should see output similar to:

[source,console]
----
$ ./gradlew execute
:compileJava
:processResources
:classes
:execute
13:32:25.339 [main] INFO  c.d.o.d.i.c.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.0.1-alpha4-SNAPSHOT
13:32:25.682 [poc-admin-0] INFO  c.d.o.d.internal.core.time.Clock - Using native clock for microsecond precision
13:32:25.683 [poc-admin-0] INFO  c.d.o.d.i.c.metadata.MetadataManager - [poc] No contact points provided, defaulting to /127.0.0.1:9042
3.11.2

BUILD SUCCESSFUL
----

=== Manually (from the binary tarball)

If your build tool can't fetch dependencies from Maven central, we publish a binary tarball on the  http://downloads.datastax.com/java-driver/[DataStax download server].

The driver and its dependencies must be in the compile-time classpath.
Application resources, such as `application.conf` and `logback.xml` in our previous examples, must be in the runtime classpath.

== JPMS support

All the driver's artifacts are JPMS automatic modules.

== Driver dependencies

The driver depends on a number of third-party libraries;
some of those dependencies are opt-in, while others are present by default, but may be excluded under specific circumstances.

Here's a rundown of what you can customize:

=== Netty

https://netty.io/[Netty] is the NIO framework that powers the driver's networking layer.

It is a required dependency, but we provide a a xref:core/shadedJar.adoc[shaded JAR] that relocates it to a different Java package;
this is useful to avoid dependency hell if you already use Netty in another part of your application.

=== Typesafe config

https://lightbend.github.io/config/[Typesafe config] is used for our file-based xref:core/configuration.adoc[configuration].

It is a required dependency if you use the driver's built-in configuration loader, but this can be xref:core/configuration.adoc#bypassing-typesafe-config[completely overridden] with your own implementation, that could use a different framework or an ad-hoc solution.

In that case, you can exclude the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>com.typesafe</groupId>
      <artifactId>config</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

=== Native libraries

The driver performs native calls with https://github.com/jnr[JNR].
This is used in two cases:

* to access a microsecond-precision clock in xref:core/queryTimestamps.adoc[timestamp generators];
* to get the process ID when generating https://docs.datastax.com/en/drivers/java/4.13/com/datastax/oss/driver/api/core/uuid/Uuids.html[UUIDs].

In both cases, this is completely optional;
if system calls are not available on the current platform, or the library fails to load for any reason, the driver falls back to pure Java workarounds.

If you don't want to use system calls, or already know (from looking at the driver's logs) that they are not available on your platform, you can exclude the following dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>com.github.jnr</groupId>
      <artifactId>jnr-posix</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

=== Compression libraries

The driver supports compression with either https://github.com/jpountz/lz4-java[LZ4] or http://google.github.io/snappy/[Snappy].

These dependencies are optional;
you have to add them explicitly in your application in order to enable compression.
See the xref:core/compression.adoc[Compression] page for more details.

=== Metrics

The driver exposes xref:core/metrics.adoc[metrics] through the http://metrics.dropwizard.io/4.1.2/[Dropwizard] library.

The dependency is declared as required, but metrics are optional.
If you've disabled all metrics, or if you are using a different metrics library, and you never call https://docs.datastax.com/en/drivers/java/4.13/com/datastax/oss/driver/api/core/session/Session.html#getMetrics--[Session.getMetrics] anywhere in your application, then you can remove the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>io.dropwizard.metrics</groupId>
      <artifactId>metrics-core</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

In addition, when using Dropwizard, "timer" metrics use http://hdrhistogram.github.io/HdrHistogram/[HdrHistogram] to record latency percentiles.
At the time of writing, these metrics are: `cql-requests`, `throttling.delay` and `cql-messages`;
you can also identify them by reading the comments in the xref:core/configurationReference.adoc[configuration reference] (look for "exposed as a Timer").

If all of these metrics are disabled, or if you use a different metrics library, you can remove the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.hdrhistogram</groupId>
      <artifactId>HdrHistogram</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

=== Jackson

https://github.com/FasterXML/jackson[Jackson] is used when:

* connecting to xref:core/cloud.adoc[Datastax Astra];
* Insights monitoring is enabled;
* xref:core/customCodecs.adoc[JSON codecs] are being used.

Jackson is declared as a required dependency, but the driver can operate normally without it.
If you don't use any of the above features, you can safely exclude the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>com.fasterxml.jackson.core</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

=== Esri

Our xref:core/dse/geotypes.adoc[geospatial types] implementation is based on the https://github.com/Esri/geometry-api-java[Esri Geometry API].

For driver versions >= 4.4.0 and < 4.14.0 Esri is declared as a required dependency,
although the driver can operate normally without it. If you don't use geospatial types
anywhere in your application, you can exclude the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
   <exclusion>
     <groupId>com.esri.geometry</groupId>
     <artifactId>*</artifactId>
   </exclusion>
  </exclusions>
</dependency>
----

Starting with driver 4.14.0, Esri has been changed to an optional dependency.  If the dependency is not used, you 
no longer have to explicitly exclude the dependency. If you want to use the Esri
library, explicitly specify it as a dependency:

[source,xml]
----
<dependency>
  <groupId>com.esri.geometry</groupId>
  <artifactId>esri-geometry-api</artifactId>
  <version>${esri.version}</version>
</dependency>
----

In the dependency specification above, use any 1.2.x version of Esri. DataStax recommends
1.2.1. These versions are older than the current 2.x versions of the library, but they are
guaranteed to be fully compatible with DSE.

=== TinkerPop

http://tinkerpop.apache.org/[Apache TinkerPop™] is used in our xref:core/dse/graph.adoc[graph API], introduced in the OSS driver in version 4.4.0 (it was previously a feature only available in the now-retired DSE driver).

For driver versions ranging from 4.4.0 to 4.9.0 inclusive, TinkerPop is declared as a required dependency, but the driver can operate normally without it.
If you don't use the graph API at all, you can exclude the TinkerPop dependencies:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.apache.tinkerpop</groupId>
      <artifactId>*</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

Starting with driver 4.10 however, TinkerPop switched to an optional dependency.
Excluding TinkerPop explicitly is not required anymore if you don't use it.
_If you do use the graph API though, you now need to explicitly include the dependencies below in your application_:

[source,xml]
----
<dependency>
  <groupId>org.apache.tinkerpop</groupId>
  <artifactId>gremlin-core</artifactId>
  <version>${tinkerpop.version}</version>
</dependency>
<dependency>
  <groupId>org.apache.tinkerpop</groupId>
  <artifactId>tinkergraph-gremlin</artifactId>
  <version>${tinkerpop.version}</version>
</dependency>
----

If you do use graph, it is important to keep the precise TinkerPop version that the driver depends on: unlike the driver, TinkerPop does not follow semantic versioning, so even a patch version change (e.g.
3.3.0 vs 3.3.3) could introduce incompatibilities.

Here are the recommended TinkerPop versions for each driver version:+++<table>++++++<tr>++++++<th>+++Driver version+++</th>++++++<th>+++TinkerPop version+++</th>++++++</tr>+++
+++<tr>++++++<td>+++4.13.0+++</td>++++++<td>+++3.4.10+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.12.0+++</td>++++++<td>+++3.4.10+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.11.0+++</td>++++++<td>+++3.4.10+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.10.0+++</td>++++++<td>+++3.4.9+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.9.0+++</td>++++++<td>+++3.4.8+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.8.0+++</td>++++++<td>+++3.4.5+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.7.0+++</td>++++++<td>+++3.4.5+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.6.0+++</td>++++++<td>+++3.4.5+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.5.0+++</td>++++++<td>+++3.4.5+++</td>++++++</tr>+++
+++<tr>++++++<td>+++4.4.0+++</td>++++++<td>+++3.3.3+++</td>++++++</tr>++++++</table>+++

=== Reactive Streams

https://www.reactive-streams.org/[Reactive Streams] types are referenced in our xref:core/reactive.adoc[reactive API].

The Reactive Streams API is declared as a required dependency, but the driver can operate normally without it.
If you never call any of the `executeReactive` methods, you can exclude the dependency:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>org.reactivestreams</groupId>
      <artifactId>reactive-streams</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

=== Documenting annotations

The driver team uses annotations to document certain aspects of the code:

* thread safety with http://jcip.net/annotations/doc/index.html[Java Concurrency in Practice] annotations `@Immutable`, `@ThreadSafe`, `@NotThreadSafe` and `@GuardedBy`;
* nullability with https://spotbugs.github.io/[SpotBugs] annotations `@Nullable` and `@NonNull`.

This is mostly used during development;
while these annotations are retained in class files, they serve no purpose at runtime.
If you want to minimize the number of JARs in your classpath, you can exclude them:

[source,xml]
----
<dependency>
  <groupId>com.datastax.oss</groupId>
  <artifactId>java-driver-core</artifactId>
  <version>${driver.version}</version>
  <exclusions>
    <exclusion>
      <groupId>com.github.stephenc.jcip</groupId>
      <artifactId>jcip-annotations</artifactId>
    </exclusion>
    <exclusion>
      <groupId>com.github.spotbugs</groupId>
      <artifactId>spotbugs-annotations</artifactId>
    </exclusion>
  </exclusions>
</dependency>
----

However, there is one case when excluding those dependencies won't work: if you use https://docs.oracle.com/javase/8/docs/technotes/tools/windows/javac.html#sthref65[annotation processing] in your build, the Java compiler scans the entire classpath -- including the driver's classes -- and tries to load all declared annotations.
If it can't find the class for an annotation, you'll get a compiler error:

----
error: cannot access ThreadSafe
  class file for net.jcip.annotations.ThreadSafe not found
1 error
----

The workaround is to keep the dependencies.

Sometimes annotation scanning can be triggered involuntarily, if one of your dependencies declares a processor via the service provider mechanism (check the `META-INF/services` directory in the JARs).
If you are sure that you don't need any annotation processing, you can compile with the `-proc:none` option and still exclude the dependencies.

=== Mandatory dependencies

The remaining core driver dependencies are the only ones that are truly mandatory:

* the https://github.com/datastax/native-protocol[native protocol] layer.
This is essentially part of the driver code, but was externalized for reuse in other projects;
* `java-driver-shaded-guava`, a shaded version of https://github.com/google/guava[Guava].
It is relocated to a different package, and only used by internal driver code, so it should be completely transparent to third-party code;
* the https://www.slf4j.org/[SLF4J] API for xref:core/logging.adoc[logging].
