java:
  - openjdk8
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - '2.1'
  - '2.2'
  - '3.0'
  - '3.11'
build:
  - type: maven
    version: 3.2.5
    goals: verify
    properties: |
      ccm.version=$CCM_CASSANDRA_VERSION
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco: true
disable_commit_status: true
notify:
  slack: java-driver-dev-bots
