jabba:
  - oracle_jdk8
  - openjdk_jdk11
  - openjdk_jdk12
  - openjdk_jdk13
os:
  - ubuntu/bionic64/java-driver
cassandra:
  - '2.1'
  - '3.0'
  - '3.11'
  - '4.0'
  - 'dse-4.8'
  - 'dse-5.0'
  - 'dse-5.1'
  - 'dse-6.0'
  - 'dse-6.7'
  - 'dse-6.8'
schedules:
  commit:
    schedule: per_commit
    matrix:
      exclude:
        # Just run against JDK8 and latest DSE (6.7 for now, change to 6.8 when released)
        - jabba: oracle_jdk8
          cassandra: ['2.1', '3.0', '3.11', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Exclude all other JDKs
        - jabba: openjdk_jdk11
        - jabba: openjdk_jdk12
        - jabba: openjdk_jdk13
    disable_commit_status: true
    notify:
      slack: java-driver-dev-bots
  nightly:
    schedule: nightly
    matrix:
      exclude:
        # No excludes for JDK8
        # Exclude JDK11 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk11
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Exclude JDK12 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk12
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Exclude JDK13 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk13
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
    disable_commit_status: true
    notify:
      slack: java-driver-dev-bots

  adhoc:
    schedule: adhoc
    matrix:
      exclude:
        # No excludes for JDK8
        # Exclude JDK11 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk11
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Exclude JDK12 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk12
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
        # Exclude JDK13 for all but the latest Cassandra and DSE 6.7+
        - jabba: openjdk_jdk13
          cassandra: ['2.1', '3.0', 'dse-4.8', 'dse-5.0', 'dse-5.1', 'dse-6.0', 'dse-6.8']
    disable_commit_status: true
    notify:
      slack: java-driver-dev-bots
build:
  - script: |
      # Jabba default should be a JDK8 for now
      jabba use default
      export MAVEN_HOME=/home/jenkins/.mvn/apache-maven-3.3.9
      export PATH=$MAVEN_HOME/bin:$PATH
      # Build with the default JDK
      mvn -B -V install -DskipTests
      # Use the matrix JDK for testing
      jabba use $JABBA_JDK_NAME
      # Run tests against matrix JDK
      mvn -B -V verify --batch-mode --show-version -Dccm.version=$CCM_CASSANDRA_VERSION -Dccm.dse=$CCM_IS_DSE -Dproxy.path=$HOME/proxy -Dmaven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml"
  - jacoco: true
