schedules:
  commit:
    # Run short suite on commit with enough C* versions to get full protocol version coverage.
    schedule: per_commit
    matrix:
      exclude:
        - java: [openjdk6, oraclejdk7]
        - cassandra: ['2.2', '3.0']
    env_vars: |
      TEST_GROUP="short"
  nightly:
    # Run full suite nightly on change for all primary branches if they have changes.
    schedule: nightly
    branches:
      # regex matches primary branch format (2.1, 3.x, 3.0.x, 3.1.x, etc).
      include: ["/\\d+(\\.[\\dx]+)+/"]
    env_vars: |
      TEST_GROUP="long"
java:
  - openjdk6
  - oraclejdk7
  - oraclejdk8
os:
  - ubuntu/trusty64
cassandra:
  - 1.2
  - 2.0
  - 2.1
  - 2.2
  - 3.0
  - 3.9
build:
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -P$TEST_GROUP
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - type: maven
    version: 3.2.5
    goals: verify --fail-never -Pisolated
    properties: |
      com.datastax.driver.TEST_BASE_NODE_WAIT=120
      com.datastax.driver.NEW_NODE_DELAY_SECONDS=100
      cassandra.version=$CCM_CASSANDRA_VERSION
      ccm.java.home=$CCM_JAVA_HOME
      ccm.path=$CCM_JAVA_HOME/bin
      failIfNoTests=false
      maven.test.failure.ignore=true
      maven.javadoc.skip=true
  - xunit:
    - "**/target/surefire-reports/TEST-*.xml"
    - "**/target/failsafe-reports/TEST-*.xml" 
